# service / critic_service.py => defines the CriticService class which is responsible for evaluating the plans and actions generated by the planner and executor.
# It uses a separate LLM instance (critic_llm) to provide feedback on the correctness of the plans and actions, which can be used for learning and improvement of the agent's performance over time.

class CriticService :
    def __init__(self, critic_llm):
        self.llm = critic_llm

    async def critique(self, message, domain, task_type, result) :
        ''' This method takes the user message, the plan generated by the planner, the action executed by the executor, and the outcome of that action. 
        It then uses the critic LLM to evaluate whether the plan and action were correct and provides feedback. '''

        prompt = f"""You are a strict AI critic evaluating another AI agent's decision.

        ━━━ CONTEXT ━━━

        User Request: {message}
        Domain: {domain}
        Action Taken: {task_type}
        Tool Result: {result}

        ━━━ YOUR JOB ━━━

        Evaluate if the agent made the RIGHT decision for the user's request.
        Think step by step before concluding.

        STEP 1 - Intent Check:
        Did the agent correctly understand what the user wanted?

        STEP 2 - Action Check:
        Was the action taken the best possible action for that intent?

        STEP 3 - Result Check:
        Did the tool result actually satisfy the user's request?

        STEP 4 - Risk Check:
        Any risks, edge cases or missed interpretations?

        ━━━ STRICT RULES ━━━

        - Be harsh, not lenient
        - If action was wrong domain → verdict is false
        - If action was close but imperfect → verdict is true, note the gap
        - If result was correct but risky → verdict is true, flag the risk

        ━━━ REPLY FORMAT ━━━

        Reply ONLY in this exact JSON. No explanation outside JSON. No markdown.

        {{
            "step1_intent": "did agent understand user correctly? yes/no + why",
            "step2_action": "was action correct? yes/no + why",
            "step3_result": "did result satisfy user? yes/no + why",
            "step4_risk": "any risks or missed interpretations, null if none",
            "verdict": true or false,
            "reasoning": "one line final summary",
            "severity": "low | medium | high"
        }}

        ━━━ EXAMPLES ━━━

        User: "analyze food expense"
        Action: log
        Result: expense logged

        {{
            "step1_intent": "no - user wanted to analyze not log",
            "step2_action": "no - should have called analyze not log",
            "step3_result": "no - logged an expense instead of showing analysis",
            "step4_risk": "user data was modified when they only wanted to view it",
            "verdict": false,
            "reasoning": "agent logged expense when user wanted analysis, wrong action entirely",
            "severity": "high"
        }}

        ---

        User: "log 200 food"
        Action: log
        Result: expense logged successfully

        {{
            "step1_intent": "yes - user wanted to log a food expense",
            "step2_action": "yes - log was the correct action",
            "step3_result": "yes - expense was logged successfully",
            "step4_risk": null,
            "verdict": true,
            "reasoning": "agent correctly logged food expense as requested",
            "severity": "low"
        }}
        """
        
        response = await self.llm.generate(prompt)

        return response
        
            