# service / critic_service.py => defines the CriticService class which is responsible for evaluating the plans and actions generated by the planner and executor.
# It uses a separate LLM instance (critic_llm) to provide feedback on the correctness of the plans and actions, which can be used for learning and improvement of the agent's performance over time.

class CriticService :
    def __init__(self, critic_llm):
        self.llm = critic_llm

    async def critique(self, message, domain, task_type, result) :
        ''' This method takes the user message, the plan generated by the planner, the action executed by the executor, and the outcome of that action. 
        It then uses the critic LLM to evaluate whether the plan and action were correct and provides feedback. '''

        prompt = f"""You are an AI quality reviewer for a tool-using assistant.

User Request: {message}
Domain: {domain}
Action Taken: {task_type}
Tool Result: {result}

Evaluate in 4 checks:
1) intent understanding
2) action correctness
3) result usefulness
4) risks

Rules:
- Be strict but fair.
- For read-only actions (like analyze/get_budget), a total of 0 can be valid if data is empty.
- Mark verdict=false only when intent/action mismatch or result clearly fails the request.

Reply ONLY valid JSON (no markdown):
{{
  "step1_intent": "yes/no + short reason",
  "step2_action": "yes/no + short reason",
  "step3_result": "yes/no + short reason",
  "step4_risk": "risk summary or null",
  "verdict": true,
  "reasoning": "one-line summary",
  "severity": "low|medium|high"
}}
"""
        
        response = await self.llm.generate(prompt)

        return response
        
            